services:
  frontend:
    image: sgu-chatbot-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "3002:80"
    pull_policy: build
    env_file:
      - stack.env
    restart: unless-stopped
