services:
  frontend:
    image: vstep-chatbot-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    container_name: vstep-chatbot-frontend
    ports:
      - "5001:80"
    pull_policy: build
    env_file:
      - stack.env
    restart: unless-stopped
