services:
  backend:
    image: haina2410/sgu-chatbot-backend:latest
    container_name: vstep-chatbot-backend
    ports:
      - "5002:8080"
    volumes:
      - upload-dir:/upload-dir
    env_file:
      - stack.env
    restart: unless-stopped

volumes:
  upload-dir: